# Dump sharable database tables to a json file and transfer to host.
#
# To use the resulting json file, run the following command on the server
# where the data should be loaded:
#   python manage.py loaddata cloudlaunch_clouds_and_apps.json
#
# Playbook command:
#   ansible-playbook -i inventory dumpdb.yml

- hosts: cloudlaunch-webserver
  gather_facts: no
  become: yes

  vars:
    app_dir: /opt/cloudlaunch-server/django-cloudlaunch
    dump_file: /tmp/clouds_and_apps.json
    venv: /opt/cloudlaunch-server/.venv

  tasks:
    - name: Dump database data
      become_user: cloudlaunch
      command: "{{ venv }}/bin/python manage.py dumpdata --indent=2 -o {{ dump_file }} djcloudbridge.cloud djcloudbridge.region djcloudbridge.zone djcloudbridge.awscloud djcloudbridge.azurecloud djcloudbridge.gcpcloud djcloudbridge.openstackcloud djcloudbridge.awsregion djcloudbridge.azureregion djcloudbridge.gcpregion djcloudbridge.openstackregion cloudlaunch.image cloudlaunch.appcategory cloudlaunch.application cloudlaunch.applicationversion cloudlaunch.DeploymentTarget cloudlaunch.HostDeploymentTarget cloudlaunch.KubernetesDeploymentTarget cloudlaunch.CloudDeploymentTarget cloudlaunch.ApplicationVersionTargetConfig cloudlaunch.ApplicationVersionCloudConfig public_appliances.tag public_appliances.sponsor public_appliances.location public_appliances.publicservice"
      args:
        chdir: "{{ app_dir }}"

    - name: Transfer the dump file here
      fetch:
        src: "{{ dump_file }}"
        dest: ./cloudlaunch_clouds_and_apps.json
        flat: yes
