---
- name: Add latest Python and Ansible PPAs
  apt_repository:
    repo: "{{ item }}"
    update_cache: no
  with_items:
    - ppa:fkrull/deadsnakes
    - ppa:ansible/ansible

- name: Add NodeSource repository for Node.js 10.0
  apt_repository:
    repo: '{{ item }} https://deb.nodesource.com/node_10.x {{ ansible_distribution_release|lower }} main'
    state: present
    update_cache: no
  with_items:
    - deb
    - deb-src

- name: Add NodeSource apt key
  apt_key:
    id: 68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install system packages
  apt:
    pkg: "{{ item }}"
    state: latest
    install_recommends: no
    force: yes
  with_items:
    - acl
    - ansible
    - fail2ban
    - gcc
    - git-core
    - libffi-dev
    - libncurses5-dev
    - libpq-dev         # For postgres psycopg2 compilation
    - libssl-dev
    - nginx
    - nodejs
    - python-dev
    - python-psycopg2   # For postgres psycopg2 compilation
    - python3-dev
    - python3-pip
    - python3-setuptools
    - python3.5
    - python3.5-dev
    - software-properties-common
    - vim
    - virtualenv
    - wget

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - tsd
    - typings

- name: Update python-setuptools
  pip:
    name: setuptools
    state: latest
    executable: pip3

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
   - reload nginx

- name: Ensure nginx ssl dir exists
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: 0500

- name: Place SSL cert files
  copy:
    src: "../files/secret/{{ item }}"
    dest: /etc/nginx/ssl/.
    mode: 0400
  with_items: "{{ ssl_cert_files | default([]) }}"

- name: Start the nginx service
  service:
    name: nginx
    state: started
    enabled: yes
...
